import { Constants } from '$lib/types/supabase-types.js';

/**
 * dropdown based on supabase enums.
 * dropdown options that are not included here must be called via respective GET functions (ex: community group type, disability category)
 */
export const dropdownOptions = {
	/**
	 * `id` is the supabase enum, `name` is the human-friendly version
	 */
	education_status: [
		{ id: "past_student", name: "Past student" },
		{ id: "enrolled", name: "Enrolled" },
		{ id: "dropped_out", name: "Dropped out" },
		{ id: "completed", name: "Completed" },
	],
	/**
	 * education level is `varchar` in the DB, but for frontend, we will limit it to these options
	 */
	education_level: [
		"Nursery", "Kinder", "SNED", "Grade 1", "Grade 2", "Grade 3", "Grade 4", "Grade 5", "Grade 6",
		"High School", "Senior High School", "College", "ALS", "Home-based", "EIC", "Others"
	],
	/**
	 * enum generated by supabase
	 */
	education_type: Constants.public.Enums.education_type_enum,
	/**
	 * NULLABLE, enum generated by supabase
	 */
	employment_type: Constants.public.Enums.employment_type_enum,
	/**
	 * enum generated by supabase
	 */
	sex: Constants.public.Enums.sex_enum,
	/**
	 * enum generated by supabase
	 */
	income_category: Constants.public.Enums.income_category_enum
}

// not used, but keeping THESE for reference

// const options_disNature = [
// 	"ADHD",
// 	"Autism Spectrum Disorder",
// 	"Cerebral Palsy",
// 	"Cleft Lip Palate",
// 	"Cleft Palate",
// 	"Communication Disorder",
// 	"Congenital Michocephaly",
// 	"Deaf",
// 	"Down Syndrome",
// 	"Ducent Muscular Dystrophy",
// 	"Epilepsy",
// 	"GDD",
// 	"Hearing Impairment",
// 	"Hyperactive",
// 	"Intellectual",
// 	"Learning",
// 	"Low Vision",
// 	"Orthopedic",
// 	"Osteogenetic Imperfecta",
// 	"Psychosocial Disability",
// 	"Rubinstein Taybi Syndrome",
// 	"Speech",
// 	"Speech and Hearing Impairment",
// 	"Speech Delay",
// 	"Speech Problem",
// 	"Tb Spondylodiscitis of the Spine",
// 	"Visual Impairment"
// ];

// const options_disCategory = [
//     "Deaf/Hard of Hearing",
//     "Intellectual Disability",
//     "Learning Disability",
//     "Mental Disability",
//     "Physical Disability",
//     "Psychosocial Disability",
//     "Speech and Language Impairment",
//     "Visual Disability",
//     "Cancer",
//     "Rare Disease (RA10747)",
//     "Multiple Disability"
// ];  // from KAISAKA's 2024-jan-nov-list-of-children